version: '3.8'
services:
  redisserver:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      backend:
        aliases:
          - "redis"



networks:
  backend:
    driver: bridge