spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: git@github.com:YoHanKi/MSA-config.git
          ignoreLocalSshSettings: true
          private-key: |
            ${CONFIG_SERVER_PRIVATE_KEY}

server:
  port: 8071

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
