spring:
  application:
    name: config-server
  profiles:
    active: native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: git@github.com:YoHanKi/MSA-config.git
          ignoreLocalSshSettings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAn4qLkaYKQZhvgVaFIjGDM0czHm0sBWFdVyPbyNKbhDpwcoB6
            3eF509MyiwhqmIGDw4iHASrQOqzaMh4iMs7Jj/MUGARUgI8lsEpMPV2aaIgxTqGj
            FScB30XaL95s3m1cuL0YF8d3Te0EqIxVabMnxLeXXS9rR6xTiW2/WOd/pt5hmZB9
            Z7FO4RHUXkUGEn42ygrr6JQEgceo2goY8RN+RO2tSpy71GTvuAMWJB4MN9LjgGrX
            lNNgme7rT1B07bqNiXQZolg73M0oM65AhFtCX4rZ/sfXM/iLnpUiF1Nnui3iSIxP
            kewaz/SGRfSYDBZUhjN5sMnbFfJT/Fd+4A5TjMwh7I5vGZ4nCj0evHKxw7Yk9RTe
            RgghCejFx8ikwQT1pryxXpLpDbmgbqLUf3pN5iXnyxWwMwq9IKaomjwi1WVrPabh
            IEj5f/QScd5CwS4+1LNzZC3uH4TfSlVu+T9Z4OhE0aG8HVBEZvJR8waioYi6Fsvb
            US6pttK88Ia4UM+rO4bTHT1hvymlWUV2IscFbAc1HFt05E41iRZopwWCmAp7t1ho
            tVk4Uggtd38JJwM2TAkz1XJvAxccCqQ7Y04RTjs4/dqMHjhV4xEGHADw6UHJPJj6
            OPVl2lLwFQcAUgCD2hjwTQNNay1IN2Dl/Sk+iKLlreXStPCUC7xn79bYsDcCAwEA
            AQKCAgAufOfjVl8JsxnWtbfQeV3yHK6UEJqxrKfOovfBgkDnnEG006Q5sCBYLWO+
            aILrEl4rJUa1e9y2JDTmQqqTZHcON3Xk86oN1ehVAKlLflFmYT0A3Q+Qs8+TWB7W
            MPlHLNXGTO9OyoQElGp1lIK07IvLgfWcpRsdBOVIl86YYMhs/sKwxQ4Nn3hNE+1u
            VK2KyPU9FUadfDf9+whEFIolARmbiygiJB6FKq5BT8DtYEYOJCi/fCJ6TseIwzoU
            3+xaczAX29k2WYCD+9HZkU5iYtcp0ONpnqCiF6vTV0BaTKbedM1Jd30eF47OhsFz
            c+y0JPOXMTul3IO21uhLENG7BuGoIGWkKYQQS10QXkAf+nm4AH2YBaPIPQESEIu+
            m6m0DhtVQt9nlbCLlAYwYORwckqyoCKr32mptYLitlNXnXvYziWw+v1IgZk1VjYq
            T7sEs6NSYVoPmmFJsxpuQIqw5lWYFqKKgRzW9X7u07cThmbJnyKxhxdrFz+PpJ59
            LSPHILcptfp4EnKcXQa+WfvmeBkr8/Vuzk9d+r0NS1abCtns157Nfi44RJfzGyQb
            dU5L8QjOZDRTLfG+CZx85O31xEeJ0v1hji/bNfMT7RBNKWJr2FatgkcNgEuovk+8
            fwfDPbiuYwp0CzuBfRUEkTa1J07TSsrQXhjGaJlS/pYeA7Ef4QKCAQEA3pa15NCm
            7vs3iOxI+CrlEmH/qm9nMqwjKZV9DVuwZ6TILVJtUcUWCq2LsK3mX3OdTQO0v6sR
            jMggTa/vGc1psLLIO97QROtWI/1SCrz7oL/SDPb/2ckuBB7hbffI8OnEXKGgJetp
            Sz6oFSDuV6k6U4QylGrj4CktyCczc2POXNnp6xAoutW8uZlHujuTKSl/6oiRIfp2
            dzvsFLopTNJwTYE+qfxsLX8JvFZ9wIqPsIHL4HPgPH7rp4M4yfPGI8EevslzzkmT
            ttHqwgbu3Xa6qnWk8hEkSwi5Z6pwucECqxCTxNWlaV48XhQAnC7LQVwwGWKYtEDs
            pK8BH/VsOJ+JoQKCAQEAt30kwCaVmaFagU2FR6gaO0HGg10JMshDXVLZeAujNQ/j
            M8uFiFKOGZfq3F5+r6H9JebzASKkQSy+274DWhuxPailIf+lGJb+wU88vlgPPAeu
            IC7GK5SXQE8kIIppwXixLwQ25b+VUrBxAJjSQjXeaVV+M+140d/6WYkQ+rtA0JX+
            SLfZECeM7dgF3wmEapE+6PF98yFKlpuPJ0JDOghOzuZVrfbfo0Iw7CCr59qjJ+Co
            3zC/VjFZqVrJBrN+KxfmlFClO8ixNeJLHPGlpU18Em4Jd1OT6CC/zyyW3aKyAzpk
            sHGrVsc+nr/UzBXCgwOXI8TSWsGZoGaEpnJHNwna1wKCAQAlTyuz68lfW1pmp/xf
            JIl6+FQrVDr/Al1udfEdERZTeQpYlm1efGOCbK5yceOgcjeWlh1w1xK8/zpy6x9v
            ur+Rb5Yieul789pfc/GRfTXMLvrdU3V1IsSEykxM63CR+Q0B3dGDKZ9fjmQMDpYE
            uYfeQdVcjUIe66gR2YhFOiB37crIrM+26WaV0Xx1WdED4EHhpPx2ro221KNwofeU
            Od27EAPZ6EaVpaqTGAhCAretBUSQHbwjR77mOBeHukWm7pLhtdCkbi7FQRBRb2oQ
            Uvtc4RVBwd/Md+zj1GzKpfB1jfTG1GzCaZpCxqWHiExnazVgu+cOp6dCv1a37aIz
            J4KhAoIBADiyCFr/ERaJTsfJRjdf78sDhe0tIBx62KXLZbq8Dc/letSUPExlBddO
            o5k38XkfWnMNq2RcadhhlQ+c5LhA+kENDQk2TrMMZOciLqi52Os5jEoRadYpcZrD
            WWxcmFTZkBXw/W18Bw2nyyLeFYmzz2dIrVgqNjzTMi3cNkzi8yIAVrPtarqdHeSX
            7Sh/blTnUEL1627miH+EzXTZ+p/B1WgEr9CzCWMOnsM3TSa03dkCh+t+yoA9e3Di
            xl61s3RpTCvjx0pztp3psD/fQsmS6ZVgPriKMJd3Fw1Sv8L39H0e2+HRHZoQsn6m
            03/D8Xg98cNxm3XDgE6Znr83bF3LQ70CggEBAJYOdTF6CtkDLwdZRrIPrlPzad/c
            BlGmmsI2G2Ff1O4rmJsJDL8NQJK5YFfamLfw89KEQbyvAwfB5/GZEMvm5Ommt5w2
            K/LLXSDlOV+ggNzV59owbkzhIqCqGSPL6CzfdJr62lM3iVTriWyXL8oHCj8ZAjXH
            d1tjanLDpV9jtKIISMO3BBNL2Ft+3903N21Qc04IqljT5SBPzdyp1XyY08vnn9Yo
            g8MUuhXVTCN6kZxpZ9oS8wfbJx03KOrQafnfpgYq/KsyDyMNDLcG3QlRKVJDgHP2
            EVbw0EEggbQYVcmQoTlY8hP72mseGwf1E2gHoCItg3VzWOBGkArIMS5SXIg=
            -----END RSA PRIVATE KEY-----

server:
  port: 8071

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
